# Generated by Django 6.0.4 on 2026-04-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_token_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
