# Generated by Django 6.0.4 on 2026-04-12 23:19

import django.db.models.deletion
import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('vendors', '0002_inventoryevent_alter_fabricitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='OrderMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('captured_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('pending', 'Pending'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('ready', 'Ready')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='fabricrequest',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='fabricrequest',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='fabricrequest',
            name='vendor',
        ),
        migrations.RemoveField(
            model_name='ordermilestone',
            name='order',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabric',
        ),
        migrations.RemoveField(
            model_name='order',
            name='measurements',
        ),
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='current_stage',
            field=models.CharField(choices=[('pending', 'Pending'), ('cutting', 'Cutting'), ('sewing', 'Sewing'), ('finishing', 'Finishing'), ('ready', 'Ready')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=orders.models.generate_order_number, editable=False, max_length=24, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='selected_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tailor_orders', to='vendors.fabricitem'),
        ),
        migrations.AddField(
            model_name='order',
            name='title',
            field=models.CharField(default='Custom Outfit', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='total_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tailor', 'deadline'], name='orders_orde_tailor__c781c4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client', 'current_stage'], name='orders_orde_client__421765_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'current_stage'], name='orders_orde_status_b258c1_idx'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='vendors.fabricitem'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order'),
        ),
        migrations.AddField(
            model_name='ordermeasurement',
            name='captured_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captured_measurements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordermeasurement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderprogresslog',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_progress_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderprogresslog',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='orders.order'),
        ),
        migrations.DeleteModel(
            name='FabricRequest',
        ),
        migrations.DeleteModel(
            name='OrderMilestone',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='order_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='order_item_line_total_non_negative'),
        ),
    ]
