# Generated by Django 6.0.4 on 2026-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tailorprofile',
            options={'ordering': ['business_name']},
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='default_turnaround_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='tailorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
