# Generated by Django 6.0.4 on 2026-04-19 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailors', '0002_alter_tailorprofile_options_tailorprofile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudinaryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=500)),
                ('secure_url', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TailorReadyMadeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Ready-made sequin gown', max_length=200)),
                ('category', models.CharField(choices=[('womens', "Women's"), ('mens', "Men's"), ('unisex', 'Unisex')], help_text='Who is this for?', max_length=20)),
                ('size_options', models.JSONField(default=list, help_text="Available sizes: ['S', 'M', 'L', 'XL']")),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fabric_used', models.CharField(help_text='What fabric was used? e.g., Silk, Lace', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Describe the item – e.g., 'Elegant sequin gown, perfect for parties.'", max_length=500)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ManyToManyField(blank=True, related_name='tailor_products', to='tailors.cloudinaryimage')),
                ('tailor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ready_made_products', to='tailors.tailorprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
