# Generated by Django 6.0.4 on 2026-04-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientprofile',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
