# Generated by Django 6.0.4 on 2026-04-12 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('stock_in', 'Stock In'), ('stock_out', 'Stock Out'), ('adjustment', 'Adjustment'), ('checkout', 'Marketplace Checkout'), ('order_allocation', 'Tailor Order Allocation')], max_length=30)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='fabricitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-changed_at']},
        ),
        migrations.AlterModelOptions(
            name='vendorprofile',
            options={'ordering': ['business_name']},
        ),
        migrations.RemoveField(
            model_name='fabricitem',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='contact',
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='sku',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='fabricitem',
            name='unit',
            field=models.CharField(choices=[('yard', 'Yard'), ('meter', 'Meter'), ('piece', 'Piece')], default='yard', max_length=20),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='fabricitem',
            index=models.Index(fields=['vendor', 'name'], name='vendors_fab_vendor__e4fe4c_idx'),
        ),
        migrations.AddIndex(
            model_name='fabricitem',
            index=models.Index(fields=['is_public', 'is_active'], name='vendors_fab_is_publ_00f540_idx'),
        ),
        migrations.AddConstraint(
            model_name='fabricitem',
            constraint=models.UniqueConstraint(fields=('vendor', 'sku'), name='unique_fabric_sku_per_vendor'),
        ),
        migrations.AddConstraint(
            model_name='fabricitem',
            constraint=models.CheckConstraint(condition=models.Q(('stock_quantity__gte', 0)), name='fabric_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fabricitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='fabric_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='fabricitem',
            constraint=models.CheckConstraint(condition=models.Q(('low_stock_threshold__gte', 0)), name='fabric_threshold_non_negative'),
        ),
        migrations.AddField(
            model_name='inventoryevent',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventoryevent',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_events', to='vendors.fabricitem'),
        ),
        migrations.AddConstraint(
            model_name='inventoryevent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delta', 0), _negated=True), name='inventory_event_quantity_not_zero'),
        ),
    ]
