# Generated by Django 5.0.2 on 2026-02-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('fabric', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_entry', to='vendors.fabricitem')),
            ],
        ),
    ]
